[package]
name = "yewtify-example"
version = "0.1.0"
authors = ["Denis Kolodin <deniskolodin@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.60"
wasm-logger = "0.2.0"
web-sys = "0.3.37"
yew = "0.15.0"
yewtify = { path = "../.." }
